### ISSUE TITLE
Run "bare metal"?

### ISSUE THREAD

**Issue by chmeeedalf** [toverainc/willow-inference-server#101]
I would love to run this in a FreeBSD jail, instead of a docker image.  Are there any plans to support running this as a bare metal service?

**Comment by kristiankielhofner** [comment]
Given the dependencies, etc not at this time. It's certainly possible but I have no idea what would happen on FreeBSD. I assume you'll run into a lot of binary issues with some of the acceleration frameworks we use - and CUDA is likely impossible.
