### ISSUE TITLE
Running in SystemD for boot startup

### ISSUE THREAD

**Issue by maxi1134** [toverainc/willow-inference-server#102]
Hey there!

I am trying to get the inference server to start on boot on my ML machine.

I tried creating the following service

```

[Unit]
Description=Willow service

[Service]
ExecStart=/home/maxi1134/willow-inference-server/run.sh

[Install]
WantedBy=multi-user.target
```

but get the error `Jul 17 20:28:38 machinelearning run.sh[183367]: the input device is not a TTY`

Any help would be appreciated!

**Comment by nikito** [comment]
If your machine is running a normal docker daemon/service, then if you do run.sh -d it should run automatically even with reboots, no need for a separate service. Run.sh is just calling docker run. 🙂

**Comment by maxi1134** [comment]
The WISNG branch seems to work!

Thanks!
