### ISSUE TITLE
wis server unresponsive.

### ISSUE THREAD

**Issue by bert269** [toverainc/willow-inference-server#107]
I have been rebooting the wis-server nightly, just after midnight. By the end of the day, it becomes unresponsive. Willow does not connect to it anymore. I have seen this on about a daily basis.
Is there a way to test this? Ping the server for response, etc, without disconnecting the ESP-BOX and connect it to the terminal to see what the responses are. I do not use voice commands all through the day, but when I do need to use it, and there is no response on willow, then it becomes an emergency to get it solved and fixed. 
I prefer to prevent this from happening, rather than to fix it when I need it.

Any ideas on how to check the health of the wis container, periodically?

Does anyone else have this problem - in that case - where do I start debugging. Are there any logs created that may help fix this?

Thanks

**Comment by bert269** [comment]
I did notice that there was an update to the main.py code two days ago. I rebuild the wis server with the latest code and will report back in the meain time if this problem persists.

**Comment by nikito** [comment]
I've had my WIS server running for weeks without a reboot and it works perfectly, never becoming unresponsive. Are you saying the willows become unresponsive, like they won't wake up from wake word?

**Comment by bert269** [comment]
No, the willows wakes up on the wake-word, but nothing happens - they just sits there. not returning a response, aka..."I heard..." or with the response to the command. The first few times I recycled the willows, but that did not help. Then I started rebooting the WIS server and that solved the problem. I do not know how to debug this or find a solution - do not even know where to begin to look.

**Comment by nikito** [comment]
You would want to check the logs of the instance. In docker there is a command to pull the instance logs, but it's much easier if using something like portainer. That would then show what WIS was last doing, or if there was any sort of critical error.

**Comment by hamishcunningham** [comment]
Or if you start the container from the command line using utils.sh run (no
-d) you can watch what happens when you're making requests via willow

**Comment by bert269** [comment]
Thanks for the response guys. I will have to run a screen connected to the server then - to track the command coming through - thanks.

I wish I knew something about "portainer" - but I am a total noob to that - I do not even know where to start.
Do I install it on the same server as where wis are running or on a different one? And to I start wis as a container of portainer? Or do I use portainer to deploy the wis container.......so many questions.

**Comment by nikito** [comment]
Portainer is a web UI for docker that has tools to manage containers running in docker. You would have it running on the same docker server as the wis instance. I believe their site has good instructions on setting it up. 🙂 It has things like viewing logs, interactive shell, etc.

**Comment by bert269** [comment]
Thanks - I will look into this. I think the PC I have running wis, should be strong enough to do both. Thanks for the update, but until I get to portainer, I will look at the output logs: docker logs <docker-id> on the server and report back when the same thing happens.
Also - I do not know if this means anything, but up until I did the re-install of wis container yesterday, I only had one container running for wis. Now I have two: the nginx-1 and the wis-1 containers. I only had the wis-1 container before. So I do not know if I did not start everything before, or how it got like that.

Thanks - will report back when this happens again.

**Comment by bert269** [comment]
Thanks - yes, I think I have been running the previous repository for a little over a month now. I probably have started it wrong - but things were working - well sorta. I must have started it wrong from the beginning - probably why I got the errors too!
Anyway - yes, I followed the readme when I did this install of WIS.
Thanks for your help - will report back when I see strange behavior again. I have access to the logs now.

**Comment by bert269** [comment]
Upon restart of the server last night, this is the only task that came back up - Nginx did not start and my ESP-Boxes does not respond.
![image](https://github.com/toverainc/willow-inference-server/assets/18601216/4b25a0c0-3dd2-4b4a-8df0-0a1f63476242)

 looking that the portainer logs, it only started after I rebootd the server - so we will not know what what the start after the server was rebooted at midnight.

The problem was with the service at startup. It only started wis and not nginx.
I also removed the reboot from crontab.

**Comment by bert269** [comment]
Server has been up and running now for almost 48hours. I will let it sit for a few more days and report back if it hungs again. I think the problem was that NGinx was not started. Closing issue.
