### ISSUE TITLE
LLM installation issue

### ISSUE THREAD

**Issue by ccgauvin94** [toverainc/willow-inference-server#109]
Hi,

Project is absolutely awesome. However, am running into some issues (probably between the ears) trying to install Vicuna. I downloaded the 3 .bin files from here:

https://huggingface.co/lmsys/vicuna-13b-delta-v1.1

And put them in ./chatbots

Then I tried to follow the written instructions: 
`./utils shell` (I assume `./utils.sh shell`). This puts me in the docker container. 
Then I run: 
`cd chatbot`
This puts me in ./chatbot in the docker container. 
Then I run:
`./utils.sh install 13B` - this actually fails with the following error:

`You need to run this command from the host - you are in the container`

If I exit the container and try, it fails again because `utils.sh` is a directory higher. If I run `../utils.sh install 13B` from outside the container, it installs everything as normal, and seems to just ignore Vicuna. There's no log output related to Vicuna or an LLM, and from what I can tell when I start it, there's no way to use Vicuna. 

Was just hoping to get some clarification here on the installation procedure. Thanks.

**Comment by kristiankielhofner** [comment]
Thanks!

Unfortunately when we merged the most recent WIS changes I forgot to update the LLM documentation in the README (facepalm). Now that there are plenty of models on Hugging Face that don't require obtaining the LLaMA weights separately you can load them directly. 

I've updated the [README](https://github.com/toverainc/willow-inference-server/tree/main#llm) for the new (much easier) process.

**Comment by ccgauvin94** [comment]
Thanks for the quick response!

Few follow up questions:

1) When starting with TheBloke/vicuna-7B-v1.3-GPTQ, I get a handful of errors: 

``
willow-inference-server-wis-1    | The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
willow-inference-server-wis-1    | The safetensors archive passed at /root/.cache/huggingface/hub/models--TheBloke--vicuna-7B-v1.3-GPTQ/snapshots/e7466408ac3d7d3534097dcd431799c603a52be7/vicuna-7b-v1.3-GPTQ-4bit-128g.no-act.order.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
``

and also:

``
willow-inference-server-wis-1    | Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
willow-inference-server-wis-1    | pip install xformers.
willow-inference-server-wis-1    | The model 'LlamaGPTQForCausalLM' is not supported for text-generation. Supported models are ['BartForCausalLM', 'BertLMHeadModel', 'BertGenerationDecoder', 'BigBirdForCausalLM', 'BigBirdPegasusForCausalLM', 'BioGptForCausalLM', 'BlenderbotForCausalLM', 'BlenderbotSmallForCausalLM', 'BloomForCausalLM', 'CamembertForCausalLM', 'CodeGenForCausalLM', 'CpmAntForCausalLM', 'CTRLLMHeadModel', 'Data2VecTextForCausalLM', 'ElectraForCausalLM', 'ErnieForCausalLM', 'GitForCausalLM', 'GPT2LMHeadModel', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTNeoForCausalLM', 'GPTNeoXForCausalLM', 'GPTNeoXJapaneseForCausalLM', 'GPTJForCausalLM', 'LlamaForCausalLM', 'MarianForCausalLM', 'MBartForCausalLM', 'MegaForCausalLM', 'MegatronBertForCausalLM', 'MvpForCausalLM', 'OpenLlamaForCausalLM', 'OpenAIGPTLMHeadModel', 'OPTForCausalLM', 'PegasusForCausalLM', 'PLBartForCausalLM', 'ProphetNetForCausalLM', 'QDQBertLMHeadModel', 'ReformerModelWithLMHead', 'RemBertForCausalLM', 'RobertaForCausalLM', 'RobertaPreLayerNormForCausalLM', 'RoCBertForCausalLM', 'RoFormerForCausalLM', 'RwkvForCausalLM', 'Speech2Text2ForCausalLM', 'TransfoXLLMHeadModel', 'TrOCRForCausalLM', 'XGLMForCausalLM', 'XLMWithLMHeadModel', 'XLMProphetNetForCausalLM', 'XLMRobertaForCausalLM', 'XLMRobertaXLForCausalLM', 'XLNetLMHeadModel', 'XmodForCausalLM'].
``

Are these normal?

2)  It's possible I misunderstood what the LLM is doing here. If I go to https://192.168.68.53:19000/api/docs#/, I see the nice UI and can submit text questions and watch those pop up in the stdout on the server. But if I say something to my Espressif, it simply submits it as a TTS request to the server, but the LLM doesn't pick it up, and nothing happens. Similarly, there's no audio playback from the Espressif box. My impression was that it would go Espressif --> STT --> Text input to LLM --> Inference --> TTS --> Espressif

but perhaps I assumed that? 

Thanks again!

**Comment by nikito** [comment]
Presently the LLM chatbot is exposed only through API, there doesn't appear to be any hook from willow into the chatbot yet. Not sure what the future plan is, but I Imagine once 1.0 is released and the team starts looking into things like Rasa for routing to skills or apps, LLM could be one of the things requests could be routed to if it is determined they are not destined for HA (IE there could be some sort of system where if it sees there's no intent match at HA it would then fall back to passing the spoken text to the LLM if desired).
