### ISSUE TITLE
utils.sh install stage-0 1/8 - fails with "no space left on device"

### ISSUE THREAD

**Issue by keith721** [toverainc/willow-inference-server#131]
Had been waiting for some months, and started clean again tonight, attempting to setup WIS from scratch again.  Installed Debian 12 Bookworm, install nvidia firmware and drivers, rebooted.  Executed `utils.sh install` and all the docker lines were progressing nicely until the error message appeared.

_Platform_: Intel i7 Alder Lake 64-bit
_VGA_: GeForce RTX 3060 12GB VRAM
_OS_: Debian 12 Bookworm

**Error message:**
```
------
 > [stage-0 1/8] FROM nvcr.io/nvidia/tensorrt:22.12-py3@sha256:d07df947208a069ce111b86d5b7044aa802bb26f67eebaa62b7ab08dd8d836e8:
------
Dockerfile:1
--------------------
   1 | >>> FROM nvcr.io/nvidia/tensorrt:22.12-py3
   2 |
   3 |     WORKDIR /app
--------------------
ERROR: failed to solve: failed to register layer: write /usr/local/cuda-11.8/targets/x86_64-linux/lib/libcusolver.so.11.4.1.48: no space left on device
```
I presume it's running out of space within the Docker container?  Should I wipe the directory and start over?

**Comment by nikito** [comment]
Yes this error means it ran out of space while writing the container. The vm/host where you are building would need more space added. 🙂

**Comment by keith721** [comment]
Ordinarily I'd find out what was eating up all the space, but in this case it doesn't appear any device is anwhere near full.   It's a 1 TB SSD, and everything previously unwrapped and installed leaving plenty of space.  FYI, I'm installing WIS on /home/willow/willow-inference-server.  /home has 836 GB free at the moment.

Only thing I can think is, /usr is on the root partition, only 18 GB with 3.6 GB used.   If the nVidia cuda libraries in /usr/local/cuda-11.8/ are consuming  almost 15 GB, that would explain it.
```
ERROR: failed to solve: failed to register layer: write /usr/local/cuda-11.8/targets/x86_64-linux/lib/libcusolver.so.11.4.1.48: no space left on device

Filesystem      Size  Used Avail Use% Mounted on
udev            7.8G     0  7.8G   0% /dev
tmpfs           1.6G  1.8M  1.6G   1% /run
/dev/nvme0n1p2   23G  3.6G   18G  17% /
tmpfs           7.8G     0  7.8G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/nvme0n1p5  1.8G   48K  1.7G   1% /tmp
/dev/nvme0n1p3  9.1G  883M  7.8G  11% /var
/dev/nvme0n1p6  881G   60M  836G   1% /home
/dev/nvme0n1p1  511M  5.9M  506M   2% /boot/efi
```

**Comment by nikito** [comment]
That's all I could surmise at this point as well. The CUDA libraries can be quite large as well as the models and tensors downloaded.

**Comment by keith721** [comment]
I went ahead and re-installed Debian 12, choosing to put all directories on a single partition.  It seems to be moving through the install now.  Thank you, @nikito for your kind assistance.
