### ISSUE TITLE
Is native Windows support possible?

### ISSUE THREAD

**Issue by strich** [toverainc/willow-inference-server#138]
I see there is a path to getting this working on Windows via the linux subsystem, but it would be nice to see it work on native windows. Is it achievable or are there quite a number of core components only available on linux?

**Comment by kristiankielhofner** [comment]
Unfortunately native Windows support just isn't possible, and even if we were somehow able to throw something together it would at best "kind of work". We use a tremendous amount of Linux-specific performance optimizations and tools with WIS that are crucial to enabling our high quality user experience and overall goals.
