### ISSUE TITLE
Running out of Memory on Install

### ISSUE THREAD

**Issue by guarddog13** [toverainc/willow-inference-server#149]
I am trying to install this on my brand new Windows gaming laptop with a 12th gen Nvidia GPU. When installing I can watch the CPU cap out at 100% to an eventual fail of install with the below error. I have increased the RAM that docker uses with a .wslconfig file and it hasn't changed a thing. Is there anything I need to do or that I'm missing that could fix this and allow me to install WIS onto my laptop? See error code below. 

`
ERROR: failed to solve: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 137
`

**Comment by nikito** [comment]
How much RAM is available on the system (not just total, but RAM available to processes at the time of build)? When building out a lot of ram gets used while things are being built out; i have seen it use as much as 8-10GB while building out.

**Comment by guarddog13** [comment]
32GB of total RAM is in my system.

**Comment by nikito** [comment]
The build process for WIS can take a few hours as it has a lot of dependencies, models, and libraries to build out. In the future we plan to have pre-built docker images for this like we do with WAS, but given that WIS is still under a lot of heavy development and changes we have not got it to that point yet :)

**Comment by guarddog13** [comment]
I stopped it and restarted it and that got it going...it's cloning into models currently.

**Comment by guarddog13** [comment]
@nikito So now I got past the build. When I run it it's restarting over and over. If I try to go to the web page https://127.0.0.1:19000/api/willow, I'm getting a 502 bad gateway error.

**Comment by nikito** [comment]
Sounds like you are running docker in WSL? You may need to do some digging on that, there's a lot of difficulties on running services in WSL as windows does not automatically expose these to the host. You also will not be able to attach willow devices to the loopback address (127.0.0.1), you would need the physical host's address.
