### ISSUE TITLE
Needed sudo to build

### ISSUE THREAD

**Issue by mineshaftgap** [toverainc/willow-inference-server#62]
When running any docker command like in `./build.sh` I needed to add `sudo` to make it work, e.g.:

```
DOCKER_BUILDKIT=1 sudo docker build -t willow-inference-server:"$TAG" .
```

**Comment by kristiankielhofner** [comment]
If your user isn't in the docker group (by default) you need to be root to run docker. You can either:

1) Add your username to the docker group with something like ```sudo usermod -a -G docker $SUDO_USER```

2) Preface the ```build.sh```, etc scripts themselves with sudo:

```sudo ./build.sh```

**Comment by mineshaftgap** [comment]
LOL, I have been using docker for ten years, I know the above info ;).

I am pointing out that in order to make it more welcoming to the community, either the scripts should figure out if they need access, give an error or the README.md should explicitly note what your put above.

**Comment by kristiankielhofner** [comment]
I was going to say... It's not like I know you but I was thinking "ummmm @mineshaftgap seems like he should know this, but you never know". I just re-read and it still reads like you were personally tripped up by it :).

With willow we have a bunch of users that use podman and other rootless container implementations. They would NOT appreciate what you have proposed - dropping sudo in the script itself. I suppose it could/should go in the docs to run the scripts themselves with sudo. The hope being that the "rootless container" people know to drop sudo?

**Comment by mineshaftgap** [comment]
I probably could have written the issue a bit better, apologies :).

I was trying to use podman but it was giving me me an issue with installing the Nvidia driver so I sent the Docker route, and since I was doing in a VM hosted by Proxmox with GPU passthrough I already felt like I was pushing it.

**Comment by kristiankielhofner** [comment]
Hah, no worries!

Installing the nvidia driver? The docker container doesn't install the Nvidia driver. The Nvidia driver is on the host and the docker container uses the nvidia-container-toolkit with docker to access Nvidia hardware through the driver on the host. See the [Ubuntu deps install script](https://github.com/toverainc/willow-inference-server/blob/main/deps/ubuntu.sh) for the outline.

**Comment by mineshaftgap** [comment]
Sorry didn't mean the driver, meant the [installing the toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html).

**Comment by kristiankielhofner** [comment]
I'm more curious about the issues you are/were having with nvidia-container-toolkit. Can you elaborate there?
