### ISSUE TITLE
Building requires docker's buildx

### ISSUE THREAD

**Issue by obones** [toverainc/willow-inference-server#69]
Hello,

As I'm trying to build on an arch linux based installation with docker up and running, I was faced with the following error message:

```
ERROR: BuildKit is enabled but the buildx component is missing or broken.
       Install the buildx component to build images with BuildKit:
       https://docs.docker.com/go/buildx/
```

Installing the `docker-buildx` package fixed it, but it might be worth mentioning it in the README.

**Comment by kristiankielhofner** [comment]
Nice catch! I'm not an Arch user but I assume we can just add ```docker-buildx``` to the ```yay``` command?

**Comment by obones** [comment]
Yes, indeed, that would be enough

**Comment by zmarty** [comment]
I am using utils.sh to build/install and it also does not contain dockerx. I had to install it manually.

**Comment by zmarty** [comment]
@kristiankielhofner I think you need to also add it to deps/ubuntu.sh
