### ISSUE TITLE
Add licence file/headers

### ISSUE THREAD

**Issue by smithfred** [toverainc/willow-inference-server#74]
There's no licence information I can find about this project overall, apart from it being described as "open source" in the about section. What is the overall licence, and can you add a licence file and licence headers to the source files please? Thanks!

**Comment by smithfred** [comment]
Thanks for the rapid reply! Could maybe add a note to the README or "About" section in the meantime?

**Comment by smithfred** [comment]
This was closed but there's no LICENSE file or similar yet?

**Comment by kristiankielhofner** [comment]
Sorry, not sure how it got closed but I do know I completely forgot about it.

Added Apache 2.0 to wisng, which we be merged shortly as 1.0 in the coming weeks.

**Comment by smithfred** [comment]
Thanks for that. Minor note: the file has a `.md` extension but isn't Markdown; it should probably be renamed to  `LICENSE` or `LICENSE.txt`.
