### ISSUE TITLE
Support GPU compute that doesn't require closed-source graphics drivers

### ISSUE THREAD

**Issue by smithfred** [toverainc/willow-inference-server#75]
From the README, you are actually giving a rationale for *GPU compute generally* when explaining the choice of CUDA:

> Note that we are primarily targeting CUDA - the performance, cost, and power usage of cheap GPUs like the Tesla P4 and GTX 1060 is too good to ignore. We'll make our best effort to support CPU wherever possible for current and future functionality but our emphasis is on performant latency-sensitive tasks even with low-end GPUs like the GTX 1060/Tesla P4 (as of this writing roughly $100 USD on the used market - and plenty of stock!).

I understand that nVidia dominates the GPU market, and that CUDA is ubiquitous, but using CUDA puts your project in the ironic position of effectively *requiring* closed-source software on users' machines for usable performance, which would seem to be antithetical to Willow's stated ethos (and additionally asks users to give money to a company that's notoriously hostile to OSS).

I'm not really hugely familiar with the GPU compute landscape, but maybe a first step could be for the project to use [HIPIFY](https://github.com/ROCm-Developer-Tools/HIPIFY) to (partially?) automate the generation of HIP code, which would at least provide a performant alternative without requiring closed-source drivers and on hardware from a far more open-source friendly company - and AIUI HIP is supported on the open-source `amdgpu` driver.

I don't know what the picture is like for Intel GPU hardware, but finding a solution there would be great too, since their integrated graphics are ubiquitous and would presumably still be better than CPU-only?

There's also OpenCL of course but I don't know what the features/porting situation is like there.

**Comment by smithfred** [comment]
Thanks for the quick response.

> AMD is at least a decade behind

> Without CUDA there is simply no way (again today, in the real world)

> and again, AMD/Intel/etc GPU is a non-starter currently

Is there specific functionality that's missing from AMD's stack/HIP that precludes its use for the inference server, or would it be that it's potentially less performant/less pleasant to use but still could be sufficient on both counts (which is not to suggest that it wouldn't potentially be a significant amount of work to add support for other stacks)?

> with the tiny exception... of a binary driver used by millions of people

We differ in opinion on how tiny an exception a very large closed-source kernel module is ;) Also Alexa is also used by millions of people, so... 😅️

> a very surface-level understanding from the perspective of someone unfamiliar with the (at least) tens of millions of dollars they have invested in the open source GPU compute ecosystem

I'm not immersed in GPU compute, you're right, I've just seen the ample evidence over the years of nVidia's failures to play nice in with OSS, e.g. with driver development (reclocking), upstream APIs (EGLStreams vs. GBM). And I know that at least it's not *just* a layman's opinion that they're pretty awful, as Torvalds so (in)famously expressed.

**Comment by kristiankielhofner** [comment]
Let me try to put it simply - if you were able to get a pytorch "hello world" equivalent to run on AMD or Intel GPU compute reliably across multiple distros, kernel versions, etc over a span of months without spending days/weeks on one-off hacks, mailing lists, issue trackers, patches, etc on a regular basis you will have already achieved something the best ML engineers in the world have so far been unable to. [One of millions of examples](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2013353). Just to get pytorch to do some basic math on a GPU from AMD or Intel... At this point AMD's approach to GPU compute has been so comically inept I'm convinced they've conceded their position in this space. Intel may be able to do better over time but already requiring an ancient (in ML terms) [specific fork and patch rev of pytorch](https://github.com/intel/intel-extension-for-pytorch#gpu-version) is yet again, ridiculous and a complete non-starter.

Now start looking at higher level frameworks we leverage like [ctranslate2](https://github.com/OpenNMT/CTranslate2), [auto-gptq](https://github.com/PanQiWei/AutoGPTQ), etc that have zero support (or even plans, to my knowledge) for these platforms. Repeat this across dozens of components.

I don't want to seem dismissive, argumentative, disrespectful, or even patronizing but Willow is in a somewhat-strange position of clashing worlds - the GPU compute space where these are all well known, blatantly obvious facts and a user base who's only understanding of these issues (in many cases) comes from driving a display on their desktop - like your comment regarding EGLStreams.

**Comment by smithfred** [comment]
Thanks for the additional context. In case you know offhand of any good deep dives on the (reasons for the) current state of compute on AMD/Intel I'd be interested to know.

**Comment by kristiankielhofner** [comment]
No worries!

I'd like to point out I'm aware of these issues (and more, ugh) because I follow the "alternative" GPU compute platforms closely. I long for the day they're reasonably competitive because I don't like monopolies and I don't like the driver situation with Nvidia either. I truly wish there were a remotely competitive alternative in the space but practically speaking we're likely years away from that (if ever, sadly).

I don't know of any resources specifically but I already touched on the fundamental reason. Someone at Nvidia made the really hard, difficult, and expensive decision 15 years ago to say "We're going all in on GPGPU compute, on all of our hardware. Whatever it takes. Period.". Absent that level of consistent commitment and effort from the likes of AMD and Intel they will never get to where they need to be. Unfortunately they have the additional slow-mover challenge of going up against an entire generation of GPGPU engineers, frameworks, etc that have built on CUDA. As the issues I noted and more demonstrate they have an extremely difficult challenge.

**Comment by lordratner** [comment]
> I long for the day they're reasonably competitive because I don't like monopolies and I don't like the driver situation with Nvidia either.

It won't be that long. Definitely not in the next year, but probably a lot closer to one year than 10.

The "AI" world in investing exploded from nothing to everything with the publicity of Chat GPT. Like you said, Nvidia is a million miles ahead, but the competitors who viewed the field as niche have suddenly seen their death flash before their eyes. The amount of money that is about to be spent playing catch up is going to make our heads spin. But they will catch up. They always do.

Doesn't mean anything for WIS in the near-term, but the profits are too juicy to be ignored anymore, so Intel, AMD, and probably Apple are going to either show up or wither on the vine. I'd bet Amazon starts making acquisitions as well. And you never know what Elon is going to do next.
