### ISSUE TITLE
FR: force a specific language

### ISSUE THREAD

**Issue by SamJongenelen** [toverainc/willow-inference-server#79]
As the title says. I was able to use `detect_language` true, but I would like to force a specific language - as usage now is a bit of a hit and miss. Of course it might be planned, i just would like it to happen wit a bit of prio hence the ticket

**Comment by kristiankielhofner** [comment]
It's in the wisng branch with force_language=en or whatever the ISO code of your language is.

The Tovera hosted best effort community WIS instances aren't running wisng yet but if you're hosting your own we'd appreciate any testing!

**Comment by SamJongenelen** [comment]
I unfortunately don't have a video card in my server that is strong enough to run WIS - so I'll wait :)

**Comment by kristiankielhofner** [comment]
WIS runs CPU only.

In any case, the Tovera hosted WIS instances should be upgraded sometime next week (pending testing results). I'll also probably spin up wisng on a different URL. I'll report back here for you when I do.

As I said, we'd appreciate the testing!

**Comment by SamJongenelen** [comment]
Wow then i misread i guess, because of the benchmarks in the readme? I'm running on a NUC + an odroid n2 HomeAssistant, will try once i have some time again

**Comment by kristiankielhofner** [comment]
Good point, we'll create some CPU benchmarks. I also updated the README to mention support CPU in the first bullet line.
