### ISSUE TITLE
Upon system reboot after using nohup ./utils.sh run, the nginx docker container does not come back, and the WIS container is stuck in restarting state

### ISSUE THREAD

**Issue by nikito** [toverainc/willow-inference-server#83]
As the title says, I ran the utils.sh run command in the background, which successfully created the docker containers and had the app running. Given that the docker compose file had the container set to restart unless stopped, I figured if I rebooted the system as a test the containers would come back online on their own, but as it turns out only the WIS container came back, and the nginx one was no longer present in the container list. Seems as a result the WIS container was hung trying to restart.

I'll admit I'm not the most experienced docker user 😆 so I may be misunderstanding what is in the docker compose file. I did change the restart policy on both containers to "always" instead of "unless-stopped" and that made it so when I reboot they both come back online on their own without me having to log in and manually run the utils.sh. Just figured I'd call it out in case that is unintended, if it is intentional then please disregard 😄 

EDIT: Figure this is understood, but this is on the wisng branch not the main branch.

**Comment by kristiankielhofner** [comment]
```nohup``` with docker compose is probably not great generally. I'm weary of restart: always but I updated docker-compose for wis to have an explicit dependency on nginx.

In terms of backgrounding you can now pass docker compose args to ```./utils.sh run|start|up```. So for background you want to do:

```./utils.sh run -d```

**Comment by nikito** [comment]
Ah got it. That is my inexperience at play, I'll do this in the future. Thank you for the info!
