### ISSUE TITLE
WIS installation failed with ./deps/ubuntu.sh

### ISSUE THREAD

**Issue by bert269** [toverainc/willow-inference-server#96]
First install on a ne Ubuntu 2304 server. When running ./deps/ubuntu.sh, I get this:

bert@wis:~/willow-inference-server$ ./deps/ubuntu.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21926  100 21926    0     0  86801      0 --:--:-- --:--:-- --:--:-- 87007
# Executing docker install script, commit: c2de0811708b6d9015ed1a2c80f02c9b70c8ce7b
+ sudo -E sh -c apt-get update -qq >/dev/null
+ sudo -E sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
Scanning processes...
Scanning candidates...
Scanning processor microcode...
Scanning linux images...
+ sudo -E sh -c install -m 0755 -d /etc/apt/keyrings
+ sudo -E sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
+ sudo -E sh -c chmod a+r /etc/apt/keyrings/docker.gpg
+ sudo -E sh -c echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu lunar stable" > /etc/apt/sources.list.d/docker.list
+ sudo -E sh -c apt-get update -qq >/dev/null
+ sudo -E sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-ce-rootless-extras docker-buildx-plugin >/dev/null
Scanning processes...
Scanning candidates...
Scanning processor microcode...
Scanning linux images...
+ sudo -E sh -c docker version
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:14 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:14 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

================================================================================

To run Docker as a non-privileged user, consider setting up the
Docker daemon in rootless mode for your user:

    dockerd-rootless-setuptool.sh install

Visit https://docs.docker.com/go/rootless/ to learn about rootless mode.

To run the Docker daemon as a fully privileged service, but granting non-root
users access, refer to https://docs.docker.com/go/daemon-access/

WARNING: Access to the remote API on a privileged Docker daemon is equivalent
         to root access on the host. Refer to the 'Docker daemon attack surface'
         documentation for details: https://docs.docker.com/go/attack-surface/

================================================================================

Synchronizing state of docker.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable docker
**# Unsupported distribution!**
Check https://nvidia.github.io/libnvidia-container
Hit:1 https://download.docker.com/linux/ubuntu lunar InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu lunar InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu lunar-updates InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu lunar-backports InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu lunar-security InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
**E: Unable to locate package nvidia-container-toolkit**

The installation instructions refer to:
"Ensure you have nvidia-container-toolkit and not nvidia-docker
On Arch Linux:
yay -S libnvidia-container-tools libnvidia-container nvidia-container-toolkit docker-buildx"
Does this mean for ubuntu also, or jsut Arch Linux?

When I do: sudo apt install libnvidia-container-tools libnvidia-container nvidia-container-toolkit docker-buildx -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libnvidia-container-tools
E: Unable to locate package libnvidia-container
E: Unable to locate package nvidia-container-toolkit
E: Unable to locate package docker-buildx

Am I missing something obvious?

**Comment by nikito** [comment]
I don't think the container supports Ubuntu 23.04. Per the documentation at https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html:
![image](https://github.com/toverainc/willow-inference-server/assets/733609/e90c5a7a-9c71-49e9-9217-23c5fa019bc8)

**Comment by bert269** [comment]
Shoot!......
Thanks....

And by the way, when I went BACK to the documentation, this is what I saw:
**For CUDA support you will need to have the NVIDIA drivers for your supported hardware installed.**

**Comment by nikito** [comment]
> Shoot!...... Thanks....
> 
> And by the way, when I went BACK to the documentation, this is what I saw: **For CUDA support you will need to have the NVIDIA drivers for your supported hardware installed.**

Yeah so the host that will be running the container would need to have the legit NVIDIA drivers installed, most people are using 530 or better, I am using 530.41.03 presently.
