### ISSUE TITLE
WIS restart

### ISSUE THREAD

**Issue by bert269** [toverainc/willow-inference-server#98]
Got the wis up yesterday and tested. Amazingly fast response. Less than 450ms on 1080ti!
This morning I had to restart the wis server.

What is the process for this? After the restart I tried to execure ./run.sh, but it failed. It could not even find the willow-inference-server directory.
I basically had to restart the whole wis installation from the **git clone** to the **runs.sh**. What am I missing here, or is this how it is designed to work?
I must admit - I had to do a sudo reboot first thing this morning - could that have destroyed the previous wis installation?

**Comment by nikito** [comment]
That's a bit odd, did you switch back the directory where you cloned WIS? That's where the scripts would live to run. Note that you can pass normal docker arguments to the run.sh; if you pass -d it will install it as a docker container that automatically starts up on server reboots and is persistent. 😃

**Comment by bert269** [comment]
yes. After the reboot I wanted to re-run the run.sh script as I know that the server was not persistent as this time. But the whole wis directory was missing.
So I just execute ./run.sh -d    and that will make it persistent accross reboots?
Goign to try it right now and report back

**Comment by nikito** [comment]
Yeah that argument will make it remain even after reboots. Very strange though that the entire directory disappeared, it's just a linux directory so no reason it should just vanish like that from a reboot. Almost seems as if the disk was in ram or something and didn't persist 😮

**Comment by bert269** [comment]
No, I do not have a ramdisk, but yes, it is very strange. - let's blame it on operator error - or not enough cofffee!

Well, I did the run.sh -d, I exit from that after the server was aup ("Application startup complete") - and receive these messages:
^C[2023-06-30 13:16:33 +0000] [1] [INFO] Handling signal: int
[2023-06-30 13:16:33 +0000] [80] [INFO] Shutting down
[2023-06-30 13:16:33 +0000] [80] [INFO] Error while closing socket [Errno 9] Bad file descriptor
[2023-06-30 13:16:33 +0000] [80] [INFO] Waiting for application shutdown.
[2023-06-30 13:16:33 +0000] [80] [INFO] Willow Inference Server is stopping (this can take a while)...
[2023-06-30 13:16:33 +0000] [80] [INFO] Application shutdown complete.
[2023-06-30 13:16:33 +0000] [80] [INFO] Finished server process [80]
[2023-06-30 13:16:33 +0000] [80] [INFO] Worker exiting (pid: 80)
[2023-06-30 13:16:35 +0000] [1] [INFO] Shutting down: Master

Then I rebooted and the directory was still there. 

How can I tell is wis is running after the reboot?

Thanks.

**Comment by nikito** [comment]
Well on my environment I am running portainer, so I can see how the docker server is doing and what it is running. Otherwise you can do a docker ps -a to list all the running containers I believe.

**Comment by bert269** [comment]
I changed the run.sh from: **docker run --rm -it --gpus "$GPUS"** 
to **docker run -d --restart unless-stopped -it --gpus "$GPUS"** 
Now it starts and run in the background. Have not tested what will happen now when I reboot the server yet. Will have to add this to local.rc for restart after reboot.
